version: '3.8'

services:
  sheets-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sheets-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - neo4j_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - neo4j_network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  neo4j_network:
    driver: bridge