version: '3.8'

services:
  sheets-service:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: sheets-service-test
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - test_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j-db-test
    environment:
      NEO4J_AUTH: neo4j/password
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
